# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#GitHub Actions is a continuous integration and continuous delivery (CI/CD) platform that allows you to automate your build, test, and deployment pipeline. You can create workflows that build and test every pull request to your repository, or deploy merged pull requests to production.

name: Scala CI

on:
  pull_request:
    branches: [ "main" ] #["*"]push event, so a workflow run is triggered every time someone pushes a change to the repository or merges a pull request
    
jobs:
  build: # name of job
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        scala: [2.13.12,3.3.0]
        java: [temurin@17]
    runs-on: ${{matrix.os}}

    steps:
    - name: checkout Git repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
<<<<<<< Updated upstream
        cache: 'sbt'
=======
        cache: 'sbt' #You can speed up your sbt builds on GitHub Actions by caching various artifacts in-between the jobs.
>>>>>>> Stashed changes
    - name: Build project
      run: sbt test
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        #uses: scala-steward-org/scala-steward-action@v2
        #with:  